--
-- PostgreSQL database dump
--

\restrict 5PnhHEgtYPPkgyylygobeeTFNZmaYtUbk4QiOHUOrFA0rocctlcGXfZqauBiEhY

-- Dumped from database version 18.4 (Debian 18.4-1.pgdg13+1)
-- Dumped by pg_dump version 18.4 (Debian 18.4-1.pgdg13+1)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- Name: public; Type: SCHEMA; Schema: -; Owner: pg_database_owner
--

ALTER SCHEMA public OWNER TO pg_database_owner;

--
-- Name: SCHEMA public; Type: COMMENT; Schema: -; Owner: pg_database_owner
--

COMMENT ON SCHEMA public IS 'standard public schema';


SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: author; Type: TABLE; Schema: public; Owner: items_user
--

CREATE TABLE public.author (
    id bigint NOT NULL,
    name character varying(100) NOT NULL,
    surname character varying(100),
    created_at timestamp(6) without time zone,
    updated_at timestamp(6) without time zone,
    version integer
);


ALTER TABLE public.author OWNER TO items_user;

--
-- Name: author_id_seq; Type: SEQUENCE; Schema: public; Owner: items_user
--

ALTER TABLE public.author ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.author_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: book; Type: TABLE; Schema: public; Owner: items_user
--

CREATE TABLE public.book (
    id bigint NOT NULL,
    title character varying(255) NOT NULL,
    year_of_publication integer,
    cover_type character varying(100),
    serial_number character varying(20),
    edition_number integer,
    catalog_number character varying(20),
    note character varying(500),
    publisher_id bigint,
    storage_id bigint,
    created_at timestamp(6) without time zone,
    updated_at timestamp(6) without time zone,
    version integer
);


ALTER TABLE public.book OWNER TO items_user;

--
-- Name: book_authors; Type: TABLE; Schema: public; Owner: items_user
--

CREATE TABLE public.book_authors (
    authors_id bigint CONSTRAINT book_author_authors_id_not_null NOT NULL,
    books_id bigint CONSTRAINT book_author_books_id_not_null NOT NULL
);


ALTER TABLE public.book_authors OWNER TO items_user;

--
-- Name: book_categories; Type: TABLE; Schema: public; Owner: items_user
--

CREATE TABLE public.book_categories (
    categories_id bigint CONSTRAINT book_category_categories_id_not_null NOT NULL,
    books_id bigint CONSTRAINT book_category_books_id_not_null NOT NULL
);


ALTER TABLE public.book_categories OWNER TO items_user;

--
-- Name: book_id_seq; Type: SEQUENCE; Schema: public; Owner: items_user
--

ALTER TABLE public.book ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.book_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: category; Type: TABLE; Schema: public; Owner: items_user
--

CREATE TABLE public.category (
    id bigint NOT NULL,
    name character varying(255) NOT NULL,
    created_at timestamp(6) without time zone,
    updated_at timestamp(6) without time zone,
    version integer
);


ALTER TABLE public.category OWNER TO items_user;

--
-- Name: category_id_seq; Type: SEQUENCE; Schema: public; Owner: items_user
--

ALTER TABLE public.category ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.category_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: flyway_schema_history; Type: TABLE; Schema: public; Owner: items_user
--

CREATE TABLE public.flyway_schema_history (
    installed_rank integer NOT NULL,
    version character varying(50),
    description character varying(200) NOT NULL,
    type character varying(20) NOT NULL,
    script character varying(1000) NOT NULL,
    checksum integer,
    installed_by character varying(100) NOT NULL,
    installed_on timestamp without time zone DEFAULT now() NOT NULL,
    execution_time integer NOT NULL,
    success boolean NOT NULL
);


ALTER TABLE public.flyway_schema_history OWNER TO items_user;

--
-- Name: item; Type: TABLE; Schema: public; Owner: items_user
--

CREATE TABLE public.item (
    id bigint NOT NULL,
    description character varying(255) NOT NULL,
    note character varying(1000),
    storage_id bigint,
    created_at timestamp(6) without time zone,
    updated_at timestamp(6) without time zone,
    version integer
);


ALTER TABLE public.item OWNER TO items_user;

--
-- Name: item_categories; Type: TABLE; Schema: public; Owner: items_user
--

CREATE TABLE public.item_categories (
    categories_id bigint CONSTRAINT item_category_categories_id_not_null NOT NULL,
    items_id bigint CONSTRAINT item_category_items_id_not_null NOT NULL
);


ALTER TABLE public.item_categories OWNER TO items_user;

--
-- Name: item_id_seq; Type: SEQUENCE; Schema: public; Owner: items_user
--

ALTER TABLE public.item ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.item_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: publisher; Type: TABLE; Schema: public; Owner: items_user
--

CREATE TABLE public.publisher (
    id bigint NOT NULL,
    name character varying(255) NOT NULL,
    created_at timestamp(6) without time zone,
    updated_at timestamp(6) without time zone,
    version integer
);


ALTER TABLE public.publisher OWNER TO items_user;

--
-- Name: publisher_id_seq; Type: SEQUENCE; Schema: public; Owner: items_user
--

ALTER TABLE public.publisher ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.publisher_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: storage; Type: TABLE; Schema: public; Owner: items_user
--

CREATE TABLE public.storage (
    id bigint NOT NULL,
    name character varying(255) NOT NULL,
    note character varying(500),
    parent_id bigint,
    created_at timestamp(6) without time zone,
    updated_at timestamp(6) without time zone,
    version integer
);


ALTER TABLE public.storage OWNER TO items_user;

--
-- Name: storage_id_seq; Type: SEQUENCE; Schema: public; Owner: items_user
--

ALTER TABLE public.storage ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.storage_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: flyway_schema_history flyway_schema_history_pk; Type: CONSTRAINT; Schema: public; Owner: items_user
--

ALTER TABLE ONLY public.flyway_schema_history
    ADD CONSTRAINT flyway_schema_history_pk PRIMARY KEY (installed_rank);


--
-- Name: author pk_author; Type: CONSTRAINT; Schema: public; Owner: items_user
--

ALTER TABLE ONLY public.author
    ADD CONSTRAINT pk_author PRIMARY KEY (id);


--
-- Name: book pk_book; Type: CONSTRAINT; Schema: public; Owner: items_user
--

ALTER TABLE ONLY public.book
    ADD CONSTRAINT pk_book PRIMARY KEY (id);


--
-- Name: book_authors pk_book_authors; Type: CONSTRAINT; Schema: public; Owner: items_user
--

ALTER TABLE ONLY public.book_authors
    ADD CONSTRAINT pk_book_authors PRIMARY KEY (authors_id, books_id);


--
-- Name: book_categories pk_book_categories; Type: CONSTRAINT; Schema: public; Owner: items_user
--

ALTER TABLE ONLY public.book_categories
    ADD CONSTRAINT pk_book_categories PRIMARY KEY (categories_id, books_id);


--
-- Name: category pk_category; Type: CONSTRAINT; Schema: public; Owner: items_user
--

ALTER TABLE ONLY public.category
    ADD CONSTRAINT pk_category PRIMARY KEY (id);


--
-- Name: item pk_item; Type: CONSTRAINT; Schema: public; Owner: items_user
--

ALTER TABLE ONLY public.item
    ADD CONSTRAINT pk_item PRIMARY KEY (id);


--
-- Name: item_categories pk_item_categories; Type: CONSTRAINT; Schema: public; Owner: items_user
--

ALTER TABLE ONLY public.item_categories
    ADD CONSTRAINT pk_item_categories PRIMARY KEY (categories_id, items_id);


--
-- Name: publisher pk_publisher; Type: CONSTRAINT; Schema: public; Owner: items_user
--

ALTER TABLE ONLY public.publisher
    ADD CONSTRAINT pk_publisher PRIMARY KEY (id);


--
-- Name: storage pk_storage; Type: CONSTRAINT; Schema: public; Owner: items_user
--

ALTER TABLE ONLY public.storage
    ADD CONSTRAINT pk_storage PRIMARY KEY (id);


--
-- Name: category uc_category_name; Type: CONSTRAINT; Schema: public; Owner: items_user
--

ALTER TABLE ONLY public.category
    ADD CONSTRAINT uc_category_name UNIQUE (name);


--
-- Name: storage uc_storage_name; Type: CONSTRAINT; Schema: public; Owner: items_user
--

ALTER TABLE ONLY public.storage
    ADD CONSTRAINT uc_storage_name UNIQUE (name);


--
-- Name: flyway_schema_history_s_idx; Type: INDEX; Schema: public; Owner: items_user
--

CREATE INDEX flyway_schema_history_s_idx ON public.flyway_schema_history USING btree (success);


--
-- Name: book_authors fk_booaut_on_author; Type: FK CONSTRAINT; Schema: public; Owner: items_user
--

ALTER TABLE ONLY public.book_authors
    ADD CONSTRAINT fk_booaut_on_author FOREIGN KEY (authors_id) REFERENCES public.author(id) ON DELETE CASCADE;


--
-- Name: book_authors fk_booaut_on_book; Type: FK CONSTRAINT; Schema: public; Owner: items_user
--

ALTER TABLE ONLY public.book_authors
    ADD CONSTRAINT fk_booaut_on_book FOREIGN KEY (books_id) REFERENCES public.book(id) ON DELETE CASCADE;


--
-- Name: book_categories fk_boocat_on_book; Type: FK CONSTRAINT; Schema: public; Owner: items_user
--

ALTER TABLE ONLY public.book_categories
    ADD CONSTRAINT fk_boocat_on_book FOREIGN KEY (books_id) REFERENCES public.book(id) ON DELETE CASCADE;


--
-- Name: book_categories fk_boocat_on_category; Type: FK CONSTRAINT; Schema: public; Owner: items_user
--

ALTER TABLE ONLY public.book_categories
    ADD CONSTRAINT fk_boocat_on_category FOREIGN KEY (categories_id) REFERENCES public.category(id) ON DELETE CASCADE;


--
-- Name: book fk_book_on_publisher; Type: FK CONSTRAINT; Schema: public; Owner: items_user
--

ALTER TABLE ONLY public.book
    ADD CONSTRAINT fk_book_on_publisher FOREIGN KEY (publisher_id) REFERENCES public.publisher(id) ON DELETE SET NULL;


--
-- Name: book fk_book_on_storage; Type: FK CONSTRAINT; Schema: public; Owner: items_user
--

ALTER TABLE ONLY public.book
    ADD CONSTRAINT fk_book_on_storage FOREIGN KEY (storage_id) REFERENCES public.storage(id) ON DELETE SET NULL;


--
-- Name: item_categories fk_itecat_on_category; Type: FK CONSTRAINT; Schema: public; Owner: items_user
--

ALTER TABLE ONLY public.item_categories
    ADD CONSTRAINT fk_itecat_on_category FOREIGN KEY (categories_id) REFERENCES public.category(id) ON DELETE CASCADE;


--
-- Name: item_categories fk_itecat_on_item; Type: FK CONSTRAINT; Schema: public; Owner: items_user
--

ALTER TABLE ONLY public.item_categories
    ADD CONSTRAINT fk_itecat_on_item FOREIGN KEY (items_id) REFERENCES public.item(id) ON DELETE CASCADE;


--
-- Name: item fk_item_on_storage; Type: FK CONSTRAINT; Schema: public; Owner: items_user
--

ALTER TABLE ONLY public.item
    ADD CONSTRAINT fk_item_on_storage FOREIGN KEY (storage_id) REFERENCES public.storage(id) ON DELETE SET NULL;


--
-- Name: storage fk_storage_on_parent; Type: FK CONSTRAINT; Schema: public; Owner: items_user
--

ALTER TABLE ONLY public.storage
    ADD CONSTRAINT fk_storage_on_parent FOREIGN KEY (parent_id) REFERENCES public.storage(id) ON DELETE SET NULL;


--
-- PostgreSQL database dump complete
--

\unrestrict 5PnhHEgtYPPkgyylygobeeTFNZmaYtUbk4QiOHUOrFA0rocctlcGXfZqauBiEhY

