ALTER TABLE author
    ALTER COLUMN id
        SET GENERATED BY DEFAULT;

ALTER TABLE author
    ALTER COLUMN created_at TYPE TIMESTAMP(6) USING created_at::TIMESTAMP(6);

ALTER TABLE author
    ALTER COLUMN updated_at TYPE TIMESTAMP(6) USING updated_at::TIMESTAMP(6);


ALTER TABLE book
    ALTER COLUMN id
        SET GENERATED BY DEFAULT;

ALTER TABLE book
    ALTER COLUMN created_at TYPE TIMESTAMP(6) USING created_at::TIMESTAMP(6);

ALTER TABLE book
    ALTER COLUMN updated_at TYPE TIMESTAMP(6) USING updated_at::TIMESTAMP(6);

ALTER TABLE book
    DROP CONSTRAINT fk_book_on_publisher;

ALTER TABLE book
    DROP CONSTRAINT fk_book_on_storage;

ALTER TABLE book
    ADD CONSTRAINT fk_book_on_publisher
        FOREIGN KEY (publisher_id) REFERENCES publisher
            ON DELETE SET NULL;

ALTER TABLE book
    ADD CONSTRAINT fk_book_on_storage
        FOREIGN KEY (storage_id) REFERENCES storage
            ON DELETE SET NULL;


ALTER TABLE book_author
    DROP CONSTRAINT pk_bookauthor;

ALTER TABLE book_author
    ADD CONSTRAINT pk_book_authors
        PRIMARY KEY (authors_id, books_id);

ALTER TABLE book_author
    DROP CONSTRAINT fk_booaut_on_author;

ALTER TABLE book_author
    DROP CONSTRAINT fk_booaut_on_book;

ALTER TABLE book_author
    ADD CONSTRAINT fk_booaut_on_author
        FOREIGN KEY (authors_id) REFERENCES author
            ON DELETE CASCADE;

ALTER TABLE book_author
    ADD CONSTRAINT fk_booaut_on_book
        FOREIGN KEY (books_id) REFERENCES book
            ON DELETE CASCADE;


ALTER TABLE book_category
    DROP CONSTRAINT pk_bookcategory;

ALTER TABLE book_category
    ADD CONSTRAINT pk_book_categories
        PRIMARY KEY (categories_id, books_id);

ALTER TABLE book_category
    DROP CONSTRAINT fk_boocat_on_book;

ALTER TABLE book_category
    DROP CONSTRAINT fk_boocat_on_category;

ALTER TABLE book_category
    ADD CONSTRAINT fk_boocat_on_book
        FOREIGN KEY (books_id) REFERENCES book
            ON DELETE CASCADE;

ALTER TABLE book_category
    ADD CONSTRAINT fk_boocat_on_category
        FOREIGN KEY (categories_id) REFERENCES category
            ON DELETE CASCADE;


ALTER TABLE category
    ALTER COLUMN id
        SET GENERATED BY DEFAULT;

ALTER TABLE category
    ALTER COLUMN created_at TYPE TIMESTAMP(6) USING created_at::TIMESTAMP(6);

ALTER TABLE category
    ALTER COLUMN updated_at TYPE TIMESTAMP(6) USING updated_at::TIMESTAMP(6);

ALTER TABLE category
    DROP CONSTRAINT category_name_key;

ALTER TABLE category
    ADD CONSTRAINT uc_category_name
        UNIQUE (name);

ALTER TABLE item
    ALTER COLUMN id
        SET GENERATED BY DEFAULT;

ALTER TABLE item
    ALTER COLUMN created_at TYPE TIMESTAMP(6) USING created_at::TIMESTAMP(6);

ALTER TABLE item
    ALTER COLUMN updated_at TYPE TIMESTAMP(6) USING updated_at::TIMESTAMP(6);

ALTER TABLE item
    DROP CONSTRAINT fk_item_on_storage;

ALTER TABLE item
    ADD CONSTRAINT fk_item_on_storage
        FOREIGN KEY (storage_id) REFERENCES storage
            ON DELETE SET NULL;

ALTER TABLE item_category
    DROP CONSTRAINT pk_itemcategory;

ALTER TABLE item_category
    ADD CONSTRAINT pk_item_categories
        PRIMARY KEY (categories_id, items_id);

ALTER TABLE item_category
    DROP CONSTRAINT fk_itecat_on_category;

ALTER TABLE item_category
    DROP CONSTRAINT fk_itecat_on_item;

ALTER TABLE item_category
    ADD CONSTRAINT fk_itecat_on_category
        FOREIGN KEY (categories_id) REFERENCES category
            ON DELETE CASCADE;

ALTER TABLE item_category
    ADD CONSTRAINT fk_itecat_on_item
        FOREIGN KEY (items_id) REFERENCES item
            ON DELETE CASCADE;

ALTER TABLE publisher
    ALTER COLUMN id
        SET GENERATED BY DEFAULT;

ALTER TABLE publisher
    ALTER COLUMN created_at TYPE TIMESTAMP(6) USING created_at::TIMESTAMP(6);

ALTER TABLE publisher
    ALTER COLUMN updated_at TYPE TIMESTAMP(6) USING updated_at::TIMESTAMP(6);

ALTER TABLE storage
    ALTER COLUMN id
        SET GENERATED BY DEFAULT;

ALTER TABLE storage
    ALTER COLUMN created_at TYPE TIMESTAMP(6) USING created_at::TIMESTAMP(6);

ALTER TABLE storage
    ALTER COLUMN updated_at TYPE TIMESTAMP(6) USING updated_at::TIMESTAMP(6);

ALTER TABLE storage
    DROP CONSTRAINT storage_name_key;

ALTER TABLE storage
    ADD CONSTRAINT uc_storage_name
        UNIQUE (name);

ALTER TABLE storage
    DROP CONSTRAINT fk_storage_on_parent;

ALTER TABLE storage
    ADD CONSTRAINT fk_storage_on_parent
        FOREIGN KEY (parent_id) REFERENCES storage
            ON DELETE SET NULL;


ALTER TABLE book_author
    RENAME TO book_authors;

ALTER TABLE book_category
    RENAME TO book_categories;

ALTER TABLE item_category
    RENAME TO item_categories;
