ALTER TABLE author
    ALTER COLUMN created_at SET NOT NULL;

ALTER TABLE book
    ALTER COLUMN created_at SET NOT NULL;

ALTER TABLE category
    ALTER COLUMN created_at SET NOT NULL;

ALTER TABLE item
    ALTER COLUMN created_at SET NOT NULL;

ALTER TABLE publisher
    ALTER COLUMN created_at SET NOT NULL;

ALTER TABLE storage
    ALTER COLUMN created_at SET NOT NULL;

ALTER TABLE author
    ALTER COLUMN version SET NOT NULL;

ALTER TABLE book
    ALTER COLUMN version SET NOT NULL;

ALTER TABLE category
    ALTER COLUMN version SET NOT NULL;

ALTER TABLE item
    ALTER COLUMN version SET NOT NULL;

ALTER TABLE publisher
    ALTER COLUMN version SET NOT NULL;

ALTER TABLE storage
    ALTER COLUMN version SET NOT NULL;

ALTER TABLE author
    ALTER COLUMN created_at TYPE TIMESTAMP(6) WITH TIME ZONE USING created_at::TIMESTAMP(6) WITH TIME ZONE;

ALTER TABLE author
    ALTER COLUMN updated_at TYPE TIMESTAMP(6) WITH TIME ZONE USING updated_at::TIMESTAMP(6) WITH TIME ZONE;

ALTER TABLE book
    ALTER COLUMN created_at TYPE TIMESTAMP(6) WITH TIME ZONE USING created_at::TIMESTAMP(6) WITH TIME ZONE;

ALTER TABLE book
    ALTER COLUMN updated_at TYPE TIMESTAMP(6) WITH TIME ZONE USING updated_at::TIMESTAMP(6) WITH TIME ZONE;

ALTER TABLE category
    ALTER COLUMN created_at TYPE TIMESTAMP(6) WITH TIME ZONE USING created_at::TIMESTAMP(6) WITH TIME ZONE;

ALTER TABLE category
    ALTER COLUMN updated_at TYPE TIMESTAMP(6) WITH TIME ZONE USING updated_at::TIMESTAMP(6) WITH TIME ZONE;

ALTER TABLE item
    ALTER COLUMN created_at TYPE TIMESTAMP(6) WITH TIME ZONE USING created_at::TIMESTAMP(6) WITH TIME ZONE;

ALTER TABLE item
    ALTER COLUMN updated_at TYPE TIMESTAMP(6) WITH TIME ZONE USING updated_at::TIMESTAMP(6) WITH TIME ZONE;

ALTER TABLE publisher
    ALTER COLUMN created_at TYPE TIMESTAMP(6) WITH TIME ZONE USING created_at::TIMESTAMP(6) WITH TIME ZONE;

ALTER TABLE publisher
    ALTER COLUMN updated_at TYPE TIMESTAMP(6) WITH TIME ZONE USING updated_at::TIMESTAMP(6) WITH TIME ZONE;

ALTER TABLE storage
    ALTER COLUMN created_at TYPE TIMESTAMP(6) WITH TIME ZONE USING created_at::TIMESTAMP(6) WITH TIME ZONE;

ALTER TABLE storage
    ALTER COLUMN updated_at TYPE TIMESTAMP(6) WITH TIME ZONE USING updated_at::TIMESTAMP(6) WITH TIME ZONE;
